AllCops:
  Include:
    - Rakefile
    - Gemfile
    - config.ru
  Exclude:
    - Vagrantfile
    - cookbooks/**/*
    - tmp/**/*
    - db/**/*
    - bin/**/*
    - spec/support/feature_helper.rb
    - scripts/**/*
    - spec/teaspoon_env.rb
    - spec/support/fake_analytics_ruby.rb

Style/AlignParameters:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Lint/SpaceBeforeFirstArg:
  Enabled: false

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/RescueModifier:
  Enabled: false
