sudo: true
language: ruby
rvm:
  - 2.2.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
before_script:
  - sudo apt-get update
  - sudo apt-get install firefox
env:
  global:
    - TRAVIS=true
    - DISPLAY=:99.0
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
