language: ruby
rvm:
  - 2.2.3
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
addons:
  firefox: latest
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 2 # give xvfb some time to start
  - bundle exec rake -T
env:
  global:
    - TRAVIS=true
cache: bundler
gemfile:
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
